import { Tool } from '@/types';
import categoriesDb from './categories';
import featuresDb   from './features';
import tagsDb       from './tags';

const cat  = (slug: string) => categoriesDb.find(c => c.slug === slug)!;
const feat = (...names: string[]) => featuresDb.filter(f => names.includes(f.name));
const tag  = (...names: string[]) => tagsDb.filter(t => names.includes(t.name));

const tools: Tool[] = [
  // ── Conversational AI ──────────────────────────────────────
  {
    _id: 'tool-1', id: 'tool-1',
    name: 'ChatGPT',
    slug: 'chatgpt',
    shortDescription: 'The most popular AI conversational assistant by OpenAI.',
    description: 'ChatGPT is a large language model built by OpenAI. It can write essays, answer questions, summarize documents, write and debug code, create content plans, and much more. Available via web, mobile app, and API.',
    website: 'https://chat.openai.com',
    pricing: 'Freemium',
    pricingDetails: 'Free tier available. ChatGPT Plus at $20/month.',
    logo: { url: null, name: null },
    isVerified: true, isFeatured: true, isPublished: true,
    viewsCount: 48200, averageRating: 4.7, reviewsCount: 312,
    categories: [cat('conversational-ai')],
    features:   feat('API Access', 'Browser Extension', 'Mobile App', 'Multi-language Support'),
    tags:       tag('chatgpt', 'llm', 'productivity'),
    createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    _id: 'tool-2', id: 'tool-2',
    name: 'Claude',
    slug: 'claude',
    shortDescription: 'Anthropic\'s AI assistant focused on safety and helpfulness.',
    description: 'Claude is a large language model by Anthropic. It excels at nuanced writing, long-document analysis, coding, and thoughtful reasoning. Known for being helpful, harmless, and honest.',
    website: 'https://claude.ai',
    pricing: 'Freemium',
    pricingDetails: 'Free tier available. Claude Pro at $20/month.',
    logo: { url: null, name: null },
    isVerified: true, isFeatured: true, isPublished: true,
    viewsCount: 29100, averageRating: 4.8, reviewsCount: 198,
    categories: [cat('conversational-ai')],
    features:   feat('API Access', 'Multi-language Support', 'Custom Fine-tuning'),
    tags:       tag('llm', 'writing', 'research'),
    createdAt: '2024-01-02T00:00:00Z', updatedAt: '2024-01-02T00:00:00Z',
  },
  {
    _id: 'tool-3', id: 'tool-3',
    name: 'Gemini',
    slug: 'gemini',
    shortDescription: 'Google\'s multimodal AI assistant with deep search integration.',
    description: 'Gemini is Google\'s flagship AI model. It understands text, images, audio, and video. Tightly integrated with Google Search, Docs, Gmail, and Workspace.',
    website: 'https://gemini.google.com',
    pricing: 'Freemium',
    pricingDetails: 'Free. Gemini Advanced with Google One AI Premium at $19.99/month.',
    logo: { url: null, name: null },
    isVerified: true, isFeatured: false, isPublished: true,
    viewsCount: 18700, averageRating: 4.5, reviewsCount: 143,
    categories: [cat('conversational-ai')],
    features:   feat('API Access', 'Mobile App', 'Multi-language Support', 'Plugins & Integrations'),
    tags:       tag('llm', 'productivity', 'research'),
    createdAt: '2024-01-03T00:00:00Z', updatedAt: '2024-01-03T00:00:00Z',
  },

  // ── Image Generation ───────────────────────────────────────
  {
    _id: 'tool-4', id: 'tool-4',
    name: 'Midjourney',
    slug: 'midjourney',
    shortDescription: 'Generate stunning AI artwork from text prompts.',
    description: 'Midjourney is a generative AI art tool that creates high-quality images from text descriptions. Known for its artistic, painterly style. Operated through Discord.',
    website: 'https://midjourney.com',
    pricing: 'Paid',
    pricingDetails: 'Basic plan from $10/month.',
    logo: { url: null, name: null },
    isVerified: true, isFeatured: true, isPublished: true,
    viewsCount: 35600, averageRating: 4.6, reviewsCount: 247,
    categories: [cat('image-generation')],
    features:   feat('API Access', 'Custom Workflows'),
    tags:       tag('image-ai', 'design'),
    createdAt: '2024-01-04T00:00:00Z', updatedAt: '2024-01-04T00:00:00Z',
  },
  {
    _id: 'tool-5', id: 'tool-5',
    name: 'DALL·E 3',
    slug: 'dall-e-3',
    shortDescription: 'OpenAI\'s image generation model integrated into ChatGPT.',
    description: 'DALL·E 3 is OpenAI\'s image generation model. It creates highly accurate images from detailed text descriptions and is directly integrated into ChatGPT Plus.',
    website: 'https://openai.com/dall-e-3',
    pricing: 'Paid',
    pricingDetails: 'Included with ChatGPT Plus ($20/month). API pricing per image.',
    logo: { url: null, name: null },
    isVerified: true, isFeatured: true, isPublished: true,
    viewsCount: 21300, averageRating: 4.5, reviewsCount: 189,
    categories: [cat('image-generation')],
    features:   feat('API Access'),
    tags:       tag('image-ai', 'design'),
    createdAt: '2024-01-05T00:00:00Z', updatedAt: '2024-01-05T00:00:00Z',
  },
  {
    _id: 'tool-6', id: 'tool-6',
    name: 'Stable Diffusion',
    slug: 'stable-diffusion',
    shortDescription: 'Open-source image generation model you can run locally.',
    description: 'Stable Diffusion is an open-source latent diffusion model for generating images. It can be run locally on consumer hardware, giving full creative control with no usage limits.',
    website: 'https://stability.ai',
    pricing: 'Free',
    pricingDetails: 'Free and open-source. Cloud hosting options available.',
    logo: { url: null, name: null },
    isVerified: true, isFeatured: false, isPublished: true,
    viewsCount: 19800, averageRating: 4.3, reviewsCount: 156,
    categories: [cat('image-generation')],
    features:   feat('API Access', 'Custom Fine-tuning', 'Offline Mode'),
    tags:       tag('open-source', 'image-ai', 'design'),
    createdAt: '2024-01-06T00:00:00Z', updatedAt: '2024-01-06T00:00:00Z',
  },

  // ── Code Generation ─────────────────────────────────────────
  {
    _id: 'tool-7', id: 'tool-7',
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    shortDescription: 'AI pair programmer that suggests code as you type.',
    description: 'GitHub Copilot is powered by OpenAI Codex. It integrates directly into VS Code, JetBrains, and other editors to provide real-time code completions, function generation, and test writing.',
    website: 'https://github.com/features/copilot',
    pricing: 'Paid',
    pricingDetails: 'Individual at $10/month. Business at $19/user/month.',
    logo: { url: null, name: null },
    isVerified: true, isFeatured: true, isPublished: true,
    viewsCount: 31400, averageRating: 4.6, reviewsCount: 274,
    categories: [cat('code-generation')],
    features:   feat('API Access', 'Plugins & Integrations', 'Team Collaboration'),
    tags:       tag('coding', 'productivity', 'llm'),
    createdAt: '2024-01-07T00:00:00Z', updatedAt: '2024-01-07T00:00:00Z',
  },
  {
    _id: 'tool-8', id: 'tool-8',
    name: 'Cursor',
    slug: 'cursor',
    shortDescription: 'AI-first code editor built on VS Code with GPT-4.',
    description: 'Cursor is a fork of VS Code with deep AI integration. It can edit multiple files at once, understands your entire codebase, and lets you chat with your code using natural language.',
    website: 'https://cursor.sh',
    pricing: 'Freemium',
    pricingDetails: 'Free tier. Pro at $20/month.',
    logo: { url: null, name: null },
    isVerified: true, isFeatured: true, isPublished: true,
    viewsCount: 24700, averageRating: 4.8, reviewsCount: 203,
    categories: [cat('code-generation')],
    features:   feat('Custom Workflows', 'Plugins & Integrations'),
    tags:       tag('coding', 'productivity'),
    createdAt: '2024-01-08T00:00:00Z', updatedAt: '2024-01-08T00:00:00Z',
  },
  {
    _id: 'tool-9', id: 'tool-9',
    name: 'Tabnine',
    slug: 'tabnine',
    shortDescription: 'AI code completion for all major IDEs.',
    description: 'Tabnine uses AI to predict and suggest code completions. It supports over 30 programming languages and integrates with all major IDEs. Can be self-hosted for enterprise.',
    website: 'https://tabnine.com',
    pricing: 'Freemium',
    pricingDetails: 'Free basic. Pro at $12/month.',
    logo: { url: null, name: null },
    isVerified: false, isFeatured: false, isPublished: true,
    viewsCount: 11200, averageRating: 4.1, reviewsCount: 88,
    categories: [cat('code-generation')],
    features:   feat('Plugins & Integrations', 'Offline Mode', 'Team Collaboration'),
    tags:       tag('coding', 'productivity'),
    createdAt: '2024-01-09T00:00:00Z', updatedAt: '2024-01-09T00:00:00Z',
  },

  // ── AI Writing ─────────────────────────────────────────────
  {
    _id: 'tool-10', id: 'tool-10',
    name: 'Jasper',
    slug: 'jasper',
    shortDescription: 'AI writing assistant for marketing and content teams.',
    description: 'Jasper (formerly Jarvis) is an AI writing tool built for marketing teams. It generates blog posts, ad copy, social media content, and emails using GPT-4.',
    website: 'https://jasper.ai',
    pricing: 'Paid',
    pricingDetails: 'Creator plan from $49/month.',
    logo: { url: null, name: null },
    isVerified: true, isFeatured: false, isPublished: true,
    viewsCount: 14500, averageRating: 4.2, reviewsCount: 112,
    categories: [cat('ai-writing')],
    features:   feat('Team Collaboration', 'API Access', 'Custom Workflows', 'Browser Extension'),
    tags:       tag('writing', 'productivity', 'automation'),
    createdAt: '2024-01-10T00:00:00Z', updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    _id: 'tool-11', id: 'tool-11',
    name: 'Copy.ai',
    slug: 'copy-ai',
    shortDescription: 'Generate marketing copy, blog posts, and social content in seconds.',
    description: 'Copy.ai is an AI writing platform that helps teams generate first drafts 10x faster. It has templates for emails, ads, product descriptions, and long-form content.',
    website: 'https://copy.ai',
    pricing: 'Freemium',
    pricingDetails: 'Free plan. Pro from $49/month.',
    logo: { url: null, name: null },
    isVerified: true, isFeatured: false, isPublished: true,
    viewsCount: 9800, averageRating: 4.0, reviewsCount: 76,
    categories: [cat('ai-writing')],
    features:   feat('Team Collaboration', 'Multi-language Support', 'Custom Workflows'),
    tags:       tag('writing', 'productivity', 'automation'),
    createdAt: '2024-01-11T00:00:00Z', updatedAt: '2024-01-11T00:00:00Z',
  },
  {
    _id: 'tool-12', id: 'tool-12',
    name: 'Grammarly',
    slug: 'grammarly',
    shortDescription: 'AI writing assistant that checks grammar, tone, and clarity.',
    description: 'Grammarly uses AI to check spelling, grammar, punctuation, clarity, engagement, and delivery in real time. Works across browsers, documents, and email.',
    website: 'https://grammarly.com',
    pricing: 'Freemium',
    pricingDetails: 'Free. Premium from $12/month.',
    logo: { url: null, name: null },
    isVerified: true, isFeatured: false, isPublished: true,
    viewsCount: 27600, averageRating: 4.4, reviewsCount: 231,
    categories: [cat('ai-writing')],
    features:   feat('Browser Extension', 'Mobile App', 'Plugins & Integrations'),
    tags:       tag('writing', 'productivity'),
    createdAt: '2024-01-12T00:00:00Z', updatedAt: '2024-01-12T00:00:00Z',
  },

  // ── Automated Analytics ────────────────────────────────────
  {
    _id: 'tool-13', id: 'tool-13',
    name: 'Julius AI',
    slug: 'julius-ai',
    shortDescription: 'Chat with your data — AI-powered data analysis.',
    description: 'Julius AI lets you upload spreadsheets, connect databases, and ask questions in plain English. It generates charts, runs statistical analysis, and explains insights automatically.',
    website: 'https://julius.ai',
    pricing: 'Freemium',
    pricingDetails: 'Free tier. Pro at $22/month.',
    logo: { url: null, name: null },
    isVerified: false, isFeatured: false, isPublished: true,
    viewsCount: 7600, averageRating: 4.3, reviewsCount: 54,
    categories: [cat('automated-analytics')],
    features:   feat('API Access', 'Custom Workflows'),
    tags:       tag('research', 'productivity', 'no-code'),
    createdAt: '2024-01-13T00:00:00Z', updatedAt: '2024-01-13T00:00:00Z',
  },
  {
    _id: 'tool-14', id: 'tool-14',
    name: 'Obviously AI',
    slug: 'obviously-ai',
    shortDescription: 'No-code AI for predictions and data insights.',
    description: 'Obviously AI allows non-technical users to build predictive models from CSV files without writing code. Point at your data, choose what to predict, and get results.',
    website: 'https://obviously.ai',
    pricing: 'Paid',
    pricingDetails: 'Starts at $75/month.',
    logo: { url: null, name: null },
    isVerified: false, isFeatured: false, isPublished: true,
    viewsCount: 5100, averageRating: 4.0, reviewsCount: 38,
    categories: [cat('automated-analytics')],
    features:   feat('API Access', 'No-code'),
    tags:       tag('no-code', 'automation', 'research'),
    createdAt: '2024-01-14T00:00:00Z', updatedAt: '2024-01-14T00:00:00Z',
  },

  // ── Adaptive Learning ──────────────────────────────────────
  {
    _id: 'tool-15', id: 'tool-15',
    name: 'Khanmigo',
    slug: 'khanmigo',
    shortDescription: 'AI tutor from Khan Academy that guides without giving answers.',
    description: 'Khanmigo is Khan Academy\'s AI-powered tutor. It uses the Socratic method to guide students through problems step by step without just giving the answer, promoting real learning.',
    website: 'https://khanacademy.org/khan-labs',
    pricing: 'Paid',
    pricingDetails: '$4/month or $44/year for learners.',
    logo: { url: null, name: null },
    isVerified: true, isFeatured: false, isPublished: true,
    viewsCount: 8900, averageRating: 4.5, reviewsCount: 67,
    categories: [cat('adaptive-learning')],
    features:   feat('Multi-language Support', 'Mobile App'),
    tags:       tag('education', 'llm'),
    createdAt: '2024-01-15T00:00:00Z', updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    _id: 'tool-16', id: 'tool-16',
    name: 'Duolingo Max',
    slug: 'duolingo-max',
    shortDescription: 'AI-powered language learning with GPT-4 conversations.',
    description: 'Duolingo Max adds AI features to the popular language app including Explain My Answer (AI explains mistakes) and Roleplay (practice real conversations with an AI character).',
    website: 'https://duolingo.com',
    pricing: 'Paid',
    pricingDetails: 'Duolingo Max from $29.99/month.',
    logo: { url: null, name: null },
    isVerified: true, isFeatured: false, isPublished: true,
    viewsCount: 12400, averageRating: 4.4, reviewsCount: 95,
    categories: [cat('adaptive-learning')],
    features:   feat('Mobile App', 'Multi-language Support', 'Offline Mode'),
    tags:       tag('education', 'productivity'),
    createdAt: '2024-01-16T00:00:00Z', updatedAt: '2024-01-16T00:00:00Z',
  },

  // ── Productivity ───────────────────────────────────────────
  {
    _id: 'tool-17', id: 'tool-17',
    name: 'Notion AI',
    slug: 'notion-ai',
    shortDescription: 'AI writing and summarisation built into Notion.',
    description: 'Notion AI brings AI assistance directly into your Notion workspace. Write, edit, summarise, translate, and brainstorm without leaving your notes and docs.',
    website: 'https://notion.so/product/ai',
    pricing: 'Paid',
    pricingDetails: 'Add-on at $10/member/month.',
    logo: { url: null, name: null },
    isVerified: true, isFeatured: false, isPublished: true,
    viewsCount: 16800, averageRating: 4.3, reviewsCount: 134,
    categories: [cat('productivity')],
    features:   feat('Team Collaboration', 'Plugins & Integrations', 'Multi-language Support'),
    tags:       tag('productivity', 'writing', 'automation'),
    createdAt: '2024-01-17T00:00:00Z', updatedAt: '2024-01-17T00:00:00Z',
  },
  {
    _id: 'tool-18', id: 'tool-18',
    name: 'Otter.ai',
    slug: 'otter-ai',
    shortDescription: 'AI meeting transcription and notes in real time.',
    description: 'Otter.ai transcribes meetings, interviews, and lectures in real time. It identifies different speakers, captures action items, and generates summaries automatically.',
    website: 'https://otter.ai',
    pricing: 'Freemium',
    pricingDetails: 'Free 300 min/month. Pro at $16.99/month.',
    logo: { url: null, name: null },
    isVerified: true, isFeatured: false, isPublished: true,
    viewsCount: 13200, averageRating: 4.2, reviewsCount: 108,
    categories: [cat('productivity')],
    features:   feat('Mobile App', 'Team Collaboration', 'Plugins & Integrations'),
    tags:       tag('productivity', 'audio', 'automation'),
    createdAt: '2024-01-18T00:00:00Z', updatedAt: '2024-01-18T00:00:00Z',
  },

  // ── Voice & Audio ──────────────────────────────────────────
  {
    _id: 'tool-19', id: 'tool-19',
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    shortDescription: 'Ultra-realistic AI voice generation and cloning.',
    description: 'ElevenLabs creates the most natural-sounding AI voices available. It supports voice cloning from a short sample, real-time voice conversion, and a full text-to-speech API.',
    website: 'https://elevenlabs.io',
    pricing: 'Freemium',
    pricingDetails: 'Free 10k characters/month. Starter at $5/month.',
    logo: { url: null, name: null },
    isVerified: true, isFeatured: true, isPublished: true,
    viewsCount: 22100, averageRating: 4.7, reviewsCount: 178,
    categories: [cat('voice-audio')],
    features:   feat('API Access', 'Multi-language Support', 'Custom Fine-tuning'),
    tags:       tag('audio', 'automation', 'llm'),
    createdAt: '2024-01-19T00:00:00Z', updatedAt: '2024-01-19T00:00:00Z',
  },
  {
    _id: 'tool-20', id: 'tool-20',
    name: 'Suno',
    slug: 'suno',
    shortDescription: 'Generate full songs with vocals from a text prompt.',
    description: 'Suno creates complete AI-generated music tracks including instrumentals and vocals from a simple text description. Songs are royalty-free and ready to share.',
    website: 'https://suno.ai',
    pricing: 'Freemium',
    pricingDetails: 'Free 50 credits/day. Pro at $8/month.',
    logo: { url: null, name: null },
    isVerified: false, isFeatured: true, isPublished: true,
    viewsCount: 17400, averageRating: 4.5, reviewsCount: 132,
    categories: [cat('voice-audio')],
    features:   feat('Mobile App', 'API Access'),
    tags:       tag('audio', 'design'),
    createdAt: '2024-01-20T00:00:00Z', updatedAt: '2024-01-20T00:00:00Z',
  },
];

export default tools;
